### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by siddhant1912** [justinchmura/js-treeview#2]
Hey, I am a complete JS newbie, and I'm just starting a project on it. However, I tried to install your library and it's somehow always failing, please refer to the attached screenshots below.

http://imgur.com/a/T5lZl

I am using a Windows 8, 64bit OS. And have v4.4.7 of node.js and v4.0.3 of npm.

**Comment by justinchmura** [comment]
Thanks for bringing this to my attention. I think I see what's going on. I'll see if I can get a fix in quick and let you know.

**Comment by justinchmura** [comment]
I just published version [1.1.3](https://github.com/justinchmura/js-treeview/releases/tag/1.1.3) that should hopefully fix your install problems. Try `npm install js-treeview` again. If you have further issues, let me know. Sorry about that again.
