### ISSUE TITLE
Init using DOMElement

### ISSUE THREAD

**Issue by PertapaCode** [justinchmura/js-treeview#6]
Hi,

The ID option should also handle a DOMElement, or another option since the name won't make sense.

**Comment by justinchmura** [comment]
Sorry for not responding right away. This should be an easy feature to add.

**Comment by PertapaCode** [comment]
Hi,

Change [this](https://github.com/justinchmura/js-treeview/blob/b432c4175c318a1bb7f846694207730067950ca2/src/treeview.js#L60) to `var container = typeof self.node === 'object' ? self.node : document.getElementById(self.node);`

I didn't test, but should work ;)
Thank you

**Comment by justinchmura** [comment]
@PertapaCode I've published version 1.1.5. #7 hopefully will add that feature for you. If you have any further questions, let me know.

**Comment by PertapaCode** [comment]
Thank you ;)
